In [29]:
import numpy as np
import numpy.linalg
from sympy import *

In [28]:
# Matrix Addition and Subtractions

A = np.array([2,1,3])
B= np.array([4,5,1])

add = A+B
sub = B-A

print(add)
print(sub)

[6 6 4]
[ 2  4 -2]


In [35]:
# Matrix Vector Multipication and Determint
ih = np.array([2,3])
jh = np.array([4,2])
vector = np.array([1,2])
matrix = np.array([ih,jh]).transpose()

answer = matrix.dot(vector)

det = np.linalg.det(matrix)
print(answer)
print(det)

[10  7]
-8.000000000000002


In [19]:
# Matrix Multipacation
# Transformation 1
i = np.array([2,1])
j = np.array([5,2])
t1 = np.array([i,j]).transpose()
# Transformation 2
i1 = np.array([8,4])
j1 = np.array([2,3])
t2 = np.array([i1,j1]).transpose()
# Multiply
combined = t1 @ t2
print(combined)

[[36 19]
 [16  8]]


In [26]:
#x+y+z=6
#2x−y+3z=14
#x+2y−z=−2

A = np.array([[1,1,1],[2,-1,3],[1,2,-1]])
A_inv = np.linalg.inv(A)
#A_trans= A.transpose()
B=np.array([6,14,-2])

ans = A_inv @ B

print(ans)



[0.8 0.8 4.4]


In [36]:
# Inverse and Identity

A = Matrix([[1,2,1],[9,3,1],[2,1,3]])
B = Matrix([[3,2,1],[3,4,5],[2,1,3]])

Inv_A = A.inv()
inden = Inv_A @ A
print(Inv_A)
print(inden)

Matrix([[-8/39, 5/39, 1/39], [25/39, -1/39, -8/39], [-1/13, -1/13, 5/13]])
Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
