In [1]:
import numpy as np

In [3]:

basis = np.array(
 [[3, 5],
 [1, 2]]
)
# declare vector v
v = np.array([2,3])
# create new vector
# by transforming v with dot product
new_v = basis.dot(v)
print(new_v) 

[21  8]


In [6]:
# Declare i-hat and j-hat
i_hat = np.array([2, 0])
j_hat = np.array([0, 3])
# compose basis matrix using i-hat and j-hat
# also need to transpose rows into columns
basis = np.array([i_hat, j_hat]).transpose()
# declare vector v
v = np.array([1,1])
# create new vector
# by transforming v with dot product
new_v = basis.dot(v)
print(basis) # [2, 3]

[[2 0]
 [0 3]]


In [15]:
v1 = np.array([3, 5])
v2 = np.array([1, 2])
vector = np.array([2, 3])
correct = np.array([v1, v2]).transpose()
wrong = np.array([v1, v2])
print(correct)
print(wrong)

[[3 1]
 [5 2]]
[[3 5]
 [1 2]]
